BEGIN TRANSACTION;
CREATE TABLE "coffeelist" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`ncoffee`	INTEGER NOT NULL,
	`nsnacks`	INTEGER NOT NULL,
	`nwater`	INTEGER NOT NULL,
	`currbill`	INTEGER
);
COMMIT;
