"""empty message

Revision ID: 768785e3ad36
Revises: 
Create Date: 2019-06-03 15:17:06.347308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768785e3ad36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coffeeadmin', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('coffeeadmin', sa.Column('send_bill', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coffeeadmin', 'send_bill')
    op.drop_column('coffeeadmin', 'email')
    # ### end Alembic commands ###
